{
 "title": "aad-aws-sync",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Is job running",
   "type": "stat",
   "gridPos": { "h": 17, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sort(sum(aad_aws_sync_job_is_running) by (name))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Successful job count",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 5, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(aad_aws_sync_job_success_count) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Failed job count",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 5, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(aad_aws_sync_job_failed_count) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Current jobs running",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 5, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "aad_aws_sync_jobs_running", "legendFormat": "{{name}}" }
   ]
  }
 ]
}