{
 "title": "Alcide Kubernetes Advisor",
 "tags": [
  "security",
  "alcide"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "profile",
    "label": "profile",
    "query": "label_values(alcide_advisor_profile_id{source=\"advisor\"}, profileId)"
   }
  ]
 },
 "panels": [
  {
   "title": "Critical",
   "type": "singlestat",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "alcide_advisor_total_count_by_severity{severity=\"critical\",profileId=\"$profile\"}"
    }
   ]
  },
  {
   "title": "Severity By Namespace (High, Critical)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 18, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (k8s_namespace) (alcide_advisor_resource_severity_count{profileId=\"$profile\", severity=~\"critical|high\"})",
     "legendFormat": "{{ k8s_namespace }}"
    }
   ]
  },
  {
   "title": "High",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "alcide_advisor_total_count_by_severity{severity=\"high\",profileId=\"$profile\"}"
    }
   ]
  },
  {
   "title": "Medium",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "alcide_advisor_total_count_by_severity{severity=\"medium\",profileId=\"$profile\"}"
    }
   ]
  },
  {
   "title": "Findings Per Check",
   "type": "graph",
   "gridPos": { "h": 6, "w": 18, "x": 6, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(alcide_advisor_total_by_check{profileId=\"$profile\"}) without (pod)",
     "legendFormat": "{{ check_title}}"
    }
   ]
  },
  {
   "title": "Low",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 9 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "alcide_advisor_total_count_by_severity{severity=\"low\",profileId=\"$profile\"}"
    }
   ]
  },
  {
   "title": "(Critical & High) Severity Count Per Resource",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(alcide_advisor_resource_severity_count{severity=~\"critical|high\", profileId=\"$profile\"} > 0) without (pod)",
     "legendFormat": "{{severity}} | {{k8s_apikind}}.{{k8s_apigroup}}/{{k8s_apiversion}}  |  {{k8s_name}}/{{ k8s_namespace}}"
    }
   ]
  }
 ]
}