{
 "title": "Blueprints RDS Adoption",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "RDS Blueprints Adoption Current - DFDS",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(blueprints_aws_rds_db_total)) / (sum(aws_rds_db_total) / 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RDS Blueprints Database Totals - DFDS",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(blueprints_aws_rds_db_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RDS Database Totals - DFDS",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(aws_rds_db_total)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "RDS Blueprints Adoption Over Time - DFDS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(sum(blueprints_aws_rds_db_total)) / (sum(aws_rds_db_total) / 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RDS Blueprints Adoption - Per Account",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "blueprints_aws_rds_db_total", "legendFormat": "__auto" }
   ]
  }
 ]
}