{
 "title": "Cloud Engineering Adoption",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "15m",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values(kube_pod_info, cluster)"
   },
   {
    "name": "capNS",
    "label": "Capability Namespaces",
    "query": "label_values(kube_namespace_labels{cluster=\"$cluster\",label_capability_name!=\"\"},namespace)"
   }
  ]
 },
 "panels": [
  {
   "title": "Capability Kubernetes resources",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(kube_namespace_labels{label_capability_name!=\"\"})",
     "legendFormat": "Namespaces"
    },
    {
     "expr": "count(kube_deployment_labels{namespace=~\"$capNS\"})",
     "legendFormat": "Deployments"
    },
    {
     "expr": "count(kube_service_labels{namespace=~\"$capNS\"})",
     "legendFormat": "Services"
    },
    {
     "expr": "count(kube_ingress_labels{namespace=~\"$capNS\"})",
     "legendFormat": "Ingresses"
    }
   ]
  },
  {
   "title": "Capability namespaces",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(kube_namespace_labels{label_capability_name!=\"\"})",
     "legendFormat": "Capability namespaces"
    },
    { "expr": "count(kube_namespace_labels)", "legendFormat": "Total namespaces" },
    {
     "expr": "count(kube_namespace_labels{label_legacy=\"true\"})",
     "legendFormat": "Legacy capabilities"
    }
   ]
  },
  {
   "title": "Capability pods",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(kube_pod_labels{namespace=~\"$capNS\"})",
     "legendFormat": "Capability pods"
    },
    { "expr": "count(kube_pod_info)", "legendFormat": "Total pods" },
    {
     "expr": "count(kube_pod_labels{namespace=~\"$capNS\"}) / count(kube_namespace_labels{label_capability_name!=\"\"})",
     "legendFormat": "Avg. pods per capability"
    }
   ]
  },
  {
   "title": "Grafana adoption",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(kube_service_labels{service=\"grafana\",label_delivered_by=\"devex\"})",
     "legendFormat": "Grafana instances"
    },
    {
     "expr": "count(kube_namespace_labels{label_capability_name!=\"\"})",
     "legendFormat": "Capability namespaces"
    }
   ]
  },
  {
   "title": "Traefik Backend Requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(traefik_backend_requests_total[5m]))",
     "legendFormat": "Request rate"
    }
   ]
  },
  {
   "title": "Unauthorised Use of Reserved Priority Classes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(kube_pod_info{priority_class=~\"system.*\",namespace!~\"kube-system\"}) OR on() vector(0)",
     "legendFormat": "system*"
    },
    {
     "expr": "count(kube_pod_info{priority_class=~\"service-critical\",namespace!~\"kube-system\"}) OR on() vector(0)",
     "legendFormat": "service-critical"
    },
    {
     "expr": "count(kube_pod_info{priority_class=~\"cluster-monitoring\",namespace!~\"alcide|kube-system|monitoring|fluentd\"}) OR on() vector(0)",
     "legendFormat": "cluster-monitoring"
    },
    {
     "expr": "count(kube_pod_info{priority_class=~\"selfservice\",namespace!~\"selfservice|selfservice-herald-vbqkr|developerautomation-xavgy\"}) OR on() vector(0)",
     "legendFormat": "selfservice"
    }
   ]
  }
 ]
}