{
 "title": "Cluster Health",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "API server 5xx errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "reqps", "label": "Error rate" }
   ],
   "targets": [
    {
     "expr": "sum by (code) (code_resource:apiserver_request_total:rate5m{code=~\"5..\"})",
     "legendFormat": "Abs {{code}}"
    },
    {
     "expr": "(sum by (code) (code_resource:apiserver_request_total:rate5m{code=~\"5..\"}) / sum by (code) (code_resource:apiserver_request_total:rate5m)) * 100",
     "legendFormat": "Rel {{code}}"
    }
   ]
  },
  {
   "title": "Liveness probe fails",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(prober_probe_total{result=\"failed\", probe_type=\"Liveness\"}[15m])) by(node)*60*15",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Readiness probe fails",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(prober_probe_total{result=\"failed\", probe_type=\"Readiness\"}[15m])) by(node)*60*15",
     "legendFormat": "{{node}}"
    }
   ]
  }
 ]
}