{
 "title": "Cluster Capacity",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Pod Capacity",
   "type": "timeseries",
   "description": "The number of pods the cluster can provision.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "count(kube_pod_info)", "legendFormat": "Running Pods" },
    {
     "expr": "sum(kube_node_status_capacity{resource=\"pods\"})",
     "legendFormat": "Pod Capacity"
    }
   ]
  },
  {
   "title": "Pod Capacity Utilization",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_pod_info) / sum(kube_node_status_capacity{resource=\"pods\"})",
     "legendFormat": "Pod Capacity Utilization"
    }
   ]
  },
  {
   "title": "CPU Capacity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum(namespace_cpu:kube_pod_container_resource_requests:sum{})",
     "legendFormat": "CPU Requests"
    },
    {
     "expr": "sum(kube_node_status_allocatable{job=\"kube-state-metrics\",resource=\"cpu\"})",
     "legendFormat": "CPU Capacity"
    }
   ]
  },
  {
   "title": "CPU Capacity Utilization",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(namespace_cpu:kube_pod_container_resource_requests:sum{}) / sum(kube_node_status_allocatable{job=\"kube-state-metrics\",resource=\"cpu\"})",
     "legendFormat": "CPU Capacity Utilization"
    }
   ]
  },
  {
   "title": "Memory Capacity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(namespace_memory:kube_pod_container_resource_requests:sum{})",
     "legendFormat": "Memory Requests"
    },
    {
     "expr": "sum(kube_node_status_allocatable{job=\"kube-state-metrics\",resource=\"memory\"})",
     "legendFormat": "Memory Capacity"
    }
   ]
  },
  {
   "title": "Memory Capacity Utilization",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(namespace_memory:kube_pod_container_resource_requests:sum{}) / sum(kube_node_status_allocatable{job=\"kube-state-metrics\",resource=\"memory\"})",
     "legendFormat": "Memory Capacity Utilization"
    }
   ]
  }
 ]
}