{
 "title": "EC2 Credits",
 "description": "This chart shows CPU Credit balance and usage for our Kubernetes Cluster EC2 instances.",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5m",
 "panels": [
  { "title": "Graphs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Credit Balance",
   "type": "stat",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "dimensions": { "InstanceId": "*" },
     "metricName": "CPUCreditBalance",
     "namespace": "AWS/EC2",
     "period": "300",
     "region": "default",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Surplus Credit Balance",
   "type": "stat",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "dimensions": { "InstanceId": "*" },
     "metricName": "CPUSurplusCreditBalance",
     "namespace": "AWS/EC2",
     "period": "300",
     "region": "default",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Credit Usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": { "InstanceId": "*" },
     "metricName": "CPUCreditUsage",
     "namespace": "AWS/EC2",
     "period": "300",
     "region": "default",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "CPU Utilisation",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "dimensions": { "InstanceId": "*" },
     "metricName": "CPUUtilization",
     "namespace": "AWS/EC2",
     "period": "60",
     "region": "default",
     "statistics": [ "Maximum" ]
    }
   ]
  },
  { "title": "Alerts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Credit Balance",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": { "InstanceId": "*" },
     "metricName": "CPUCreditBalance",
     "namespace": "AWS/EC2",
     "period": "300",
     "region": "default",
     "statistics": [ "Average" ]
    }
   ]
  }
 ]
}