{
 "title": "EKS version",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Current cluster version",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "count(eks_version_exporter) by (server_current_version)",
     "legendFormat": "{{server_current_version}}"
    }
   ]
  },
  {
   "title": "Latest available Kubernetes release",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 3, "y": 0 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "count(eks_version_exporter) by (k8s_latest_available_version)",
     "legendFormat": "{{k8s_latest_available_version}}"
    }
   ]
  },
  {
   "title": "Latest available EKS release",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 7, "y": 0 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "count(eks_version_exporter) by (eks_latest_available_version)",
     "legendFormat": "{{eks_latest_available_version}}"
    }
   ]
  },
  {
   "title": "Oldest supported EOL Kubernetes version",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 11, "y": 0 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "count(eks_version_exporter) by (eol_latest_available_version)",
     "legendFormat": "{{eol_latest_available_version}}"
    }
   ]
  },
  {
   "title": "Last updated (UTC)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 4 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "count(eks_version_exporter) by (last_updated_text)",
     "legendFormat": "{{last_updated_text}}"
    }
   ]
  },
  {
   "title": "Is cluster version outdated",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 5, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "eks_version_exporter_is_outdated",
     "legendFormat": "is_outdated"
    }
   ]
  },
  {
   "title": "Is cluster version past EOL",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 13, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "eks_version_exporter_is_past_eol",
     "legendFormat": "is_outdated"
    }
   ]
  }
 ]
}