{
 "title": "Etcd",
 "description": "Monitors etcd in EKS and apiserver requests",
 "tags": [ "etcd" ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Etcd request latency (99th percentile)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(etcd_request_duration_seconds_bucket[5m])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Etcd DB Size",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "max(etcd_db_total_size_in_bytes)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "apiserver server requests",
   "type": "timeseries",
   "description": "Rate of total API server requests over 5mins grouped by resource",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum(code_resource:apiserver_request_total:rate5m) by (resource)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "apiserver 504 errors",
   "type": "timeseries",
   "description": "Rate of total API server requests with 504 error code over 5mins grouped by resource",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum(code_resource:apiserver_request_total:rate5m{code=\"504\"}) by (resource)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "apiserver 500 errors",
   "type": "timeseries",
   "description": "Rate of total API server requests with 500 error code over 5mins grouped by resource",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sum(code_resource:apiserver_request_total:rate5m{code=\"500\"}) by (resource)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}