{
 "title": "Fluentd",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Fluentd daemonset status",
   "type": "grafana-polystat-panel",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "count(up{pod=~\"fluentd.*\"}) by (service) - sum(up{pod=~\"fluentd.*\"}) by (service)",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Fluentd  daemonset running timeseries",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(up{pod=~\"fluentd.*\"}) by (service) - sum(up{pod=~\"fluentd.*\"}) by (service)",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Fluentd available buffer space ratio",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "fluentd_output_status_buffer_available_space_ratio",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Fluentd retry wait",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "fluentd_output_status_retry_wait",
     "legendFormat": "{{pod}} : {{type}}"
    }
   ]
  },
  {
   "title": "Fluentd number of errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "fluentd_output_status_num_errors",
     "legendFormat": "{{type}} : {{pod}}"
    }
   ]
  },
  {
   "title": "Fluentd buffer total bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "fluentd_output_status_buffer_total_bytes",
     "legendFormat": "{{pod}}:{{plugin_id}}"
    }
   ]
  },
  {
   "title": "Fluentd buffer queue length",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "fluentd_output_status_buffer_queue_length",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}