{
 "title": "Cluster: Goldpinger",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(goldpinger_instance)"
   },
   { "name": "call_type", "label": "Call Type", "query": "label_values(call_type)" }
  ]
 },
 "panels": [
  { "title": "Overall Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Goldpinger Nodes",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "(count(goldpinger_nodes_health_total{status='healthy'}) + count(goldpinger_nodes_health_total{status='unhealthy'})) /2"
    }
   ]
  },
  {
   "title": "Increase in # Errors [30m]",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(increase(goldpinger_errors_total{goldpinger_instance=~\"$instance\"}[30m]))"
    }
   ]
  },
  {
   "title": "Unhealthy seen by instance",
   "type": "table",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 1 },
   "targets": [
    {
     "expr": "sum(goldpinger_nodes_health_total{status='unhealthy'}) by (goldpinger_instance)",
     "legendFormat": "{{ goldpinger_instance }}"
    }
   ]
  },
  {
   "title": "Unhealthy nodes increase [30m]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(goldpinger_nodes_health_total{goldpinger_instance=~\"$instance\", status=\"unhealthy\"}[30m])) by (goldpinger_instance)",
     "legendFormat": "{{ goldpinger_instance }}"
    }
   ]
  },
  {
   "title": "% Unhealthy nodes reported",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(increase(goldpinger_nodes_health_total{goldpinger_instance=~\"$instance\",status=\"unhealthy\"}[30m])) by (goldpinger_instance) /  (sum(increase(goldpinger_nodes_health_total{goldpinger_instance=~\"$instance\",status=\"healthy\"}[30m])) by (goldpinger_instance) + sum(increase(goldpinger_nodes_health_total{goldpinger_instance=~\"$instance\",status=\"unhealthy\"}[30m])) by (goldpinger_instance))",
     "legendFormat": "{{ goldpinger_instance }}"
    }
   ]
  },
  { "title": "Connections to peers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "99% response time from node [30m]",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(goldpinger_peers_response_time_s_bucket{goldpinger_instance=~\"$instance\",call_type=~\"$call_type\"}[30m])) by (goldpinger_instance, le))",
     "legendFormat": "{{ goldpinger_instance }}"
    }
   ]
  },
  {
   "title": "95% response time from node [30m]",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 18 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(goldpinger_peers_response_time_s_bucket{goldpinger_instance=~\"$instance\",call_type=~\"$call_type\"}[30m])) by (goldpinger_instance, le))",
     "legendFormat": "{{ goldpinger_instance }}"
    }
   ]
  },
  {
   "title": "50% response time from node [30m]",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 18 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(goldpinger_peers_response_time_s_bucket{goldpinger_instance=~\"$instance\",call_type=~\"$call_type\"}[30m])) by (goldpinger_instance, le))",
     "legendFormat": "{{ goldpinger_instance }}"
    }
   ]
  },
  { "title": "Connections to Kubernetes API", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "99% response time from k8s api [30m]",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(goldpinger_kube_master_response_time_s_bucket{goldpinger_instance=~\"$instance\"}[30m])) by (goldpinger_instance, le))",
     "legendFormat": "{{ goldpinger_instance }}"
    }
   ]
  },
  {
   "title": "95% response time from k8s api [30m]",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 29 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(goldpinger_kube_master_response_time_s_bucket{goldpinger_instance=~\"$instance\"}[30m])) by (goldpinger_instance, le))",
     "legendFormat": "{{ goldpinger_instance }}"
    }
   ]
  },
  {
   "title": "50% response time from k8s api [30m]",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 29 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(goldpinger_kube_master_response_time_s_bucket{goldpinger_instance=~\"$instance\"}[30m])) by (goldpinger_instance, le))",
     "legendFormat": "{{ goldpinger_instance }}"
    }
   ]
  },
  { "title": "Alerting", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "Alert plot",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(goldpinger_nodes_health_total{status=\"unhealthy\"}) by (goldpinger_instance)",
     "legendFormat": "{{ goldpinger_instance }}"
    }
   ]
  }
 ]
}