{
 "title": "KIAM to IRSA tracking",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Namespaces with KIAM pod annotations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "count(kube_pod_annotations{annotation_iam_amazonaws_com_role=~\"arn:aws:iam::.+:role/.+\"}) by (namespace, job)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Main offenders",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_pod_annotations{annotation_iam_amazonaws_com_role=~\"arn:aws:iam::.+:role/.+\"}) by (namespace, job) >= 5",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Count of namespaces with KIAM annotations",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_namespace_annotations{annotation_iam_amazonaws_com_permitted=~\"arn:aws:iam::.+:role/.+\"})"
    }
   ]
  },
  {
   "title": "Count of pods with KIAM annotations",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_pod_annotations{annotation_iam_amazonaws_com_role=~\"arn:aws:iam::.+:role/.+\"})"
    }
   ]
  },
  {
   "title": "Count of namespaces with KIAM annotations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "count(kube_namespace_annotations{annotation_iam_amazonaws_com_permitted=~\"arn:aws:iam::.+:role/.+\"})",
     "legendFormat": "Count"
    }
   ]
  },
  {
   "title": "Number of pods with KIAM annotations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "count(kube_pod_annotations{annotation_iam_amazonaws_com_role=~\"arn:aws:iam::.+:role/.+\"})",
     "legendFormat": "Count"
    }
   ]
  }
 ]
}