{
 "title": "readiness / liveness probes",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "% of deployments in a namespace that are missing readiness probes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(count(k8s_readiness_probe_exists) by (exported_namespace) - sum(k8s_readiness_probe_exists) by (exported_namespace)) / count(k8s_readiness_probe_exists) by (exported_namespace) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "% of deployments in a namespace that are missing liveness probes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(count(k8s_liveness_probe_exists) by (exported_namespace) - sum(k8s_liveness_probe_exists) by (exported_namespace)) / count(k8s_liveness_probe_exists) by (exported_namespace) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Deployments - readiness probes",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(k8s_readiness_probe_exists) - sum(k8s_readiness_probe_exists)",
     "legendFormat": "Has probes"
    },
    {
     "expr": "sum(k8s_readiness_probe_exists)",
     "legendFormat": "No probes"
    }
   ]
  },
  {
   "title": "Deployments - liveness probes",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(k8s_liveness_probe_exists) - sum(k8s_liveness_probe_exists)",
     "legendFormat": "Has probes"
    },
    { "expr": "sum(k8s_liveness_probe_exists)", "legendFormat": "No probes" }
   ]
  },
  {
   "title": "Deployments - readiness probes coverage",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(count(k8s_readiness_probe_exists) - sum(k8s_readiness_probe_exists)) / count(k8s_readiness_probe_exists)",
     "legendFormat": "Has probes"
    }
   ]
  },
  {
   "title": "Deployments - liveness probes coverage",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 17, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(count(k8s_liveness_probe_exists) - sum(k8s_liveness_probe_exists)) / count(k8s_liveness_probe_exists)",
     "legendFormat": "Has probes"
    }
   ]
  },
  {
   "title": "Readiness by namespaces ",
   "type": "grafana-polystat-panel",
   "gridPos": { "h": 15, "w": 23, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sum(k8s_readiness_probe_exists) by (exported_namespace)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Liveness by namespaces ",
   "type": "grafana-polystat-panel",
   "gridPos": { "h": 15, "w": 23, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "sum(k8s_liveness_probe_exists) by (exported_namespace)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}