{
 "title": "Priority class",
 "description": "Monitoring distribution of priorityclasses",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Priority class by namespaces",
   "type": "table-old",
   "gridPos": { "h": 17, "w": 10, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "count(kube_pod_info) by (priority_class, namespace)"
    }
   ]
  },
  {
   "title": "Priority class distribution",
   "type": "bargauge",
   "gridPos": { "h": 17, "w": 13, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(kube_pod_info) by (priority_class)",
     "legendFormat": "{{priority_class}}"
    }
   ]
  },
  {
   "title": "Alert graph",
   "type": "graph",
   "gridPos": { "h": 9, "w": 10, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(kube_pod_info{priority_class=\"selfservice\", namespace!=\"selfservice\", namespace!=\"selfservice-herald-vbqkr\", namespace!=\"developerautomation-xavgy\"}) by (pririty_class, namespace)",
     "legendFormat": "Selfservice priority class"
    },
    {
     "expr": "count(kube_pod_info{priority_class=\"service-critical\", namespace!=\"kube-system\"}) by (pririty_class, namespace)",
     "legendFormat": "Service critical priority class"
    },
    {
     "expr": "count(kube_pod_info{priority_class=\"cluster-monitoring\", namespace!=\"alcide\", namespace!=\"kube-system\", namespace!=\"kube-system\", namespace!=\"monitoring\"}) by (pririty_class, namespace)",
     "legendFormat": "Cluster monitoring priority class"
    },
    {
     "expr": "count(kube_pod_info{priority_class=\"system-node-critical\", namespace!=\"kube-system\"}) by (pririty_class, namespace)",
     "legendFormat": "System node critical priority class"
    }
   ]
  }
 ]
}