{
 "title": "Traefik Migration",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "1m,5m,10m,30m,1h" }
  ]
 },
 "panels": [
  {
   "title": "Traefik service distribution %",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(rate(traefik_entrypoint_requests_total{namespace=\"traefik\"}[5m]))/sum(rate(traefik_entrypoint_requests_total[5m])))*100",
     "legendFormat": "Traefik v2 service %"
    },
    {
     "expr": "(sum(rate(traefik_entrypoint_requests_total{namespace=\"kube-system\"}[5m]))/sum(rate(traefik_entrypoint_requests_total[5m])))*100",
     "legendFormat": "Traefik v1 service %"
    }
   ]
  },
  {
   "title": "Traefik v1 request duration by backend",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(traefik_backend_request_duration_seconds_sum{protocol!=\"websocket\"}[5m])) by (backend) / sum(rate(traefik_backend_request_duration_seconds_count{protocol!=\"websocket\"}[5m])) by (backend)",
     "legendFormat": "Traefik request duration :  {{backend}}"
    }
   ]
  },
  {
   "title": "Traefik v2 request",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(traefik_entrypoint_requests_total{namespace=\"traefik\"}[$interval]))",
     "legendFormat": "Total request"
    }
   ]
  },
  {
   "title": "Traefik v1 requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(traefik_entrypoint_requests_total{namespace=\"kube-system\",service=\"traefik\"}[$interval]))",
     "legendFormat": "Total requests"
    }
   ]
  },
  {
   "title": "Traefik v2 error codes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(traefik_service_requests_total{protocol!=\"websocket\", code=~\"4..\"}[$interval])) by (code)",
     "legendFormat": "{{code}}"
    },
    {
     "expr": "sum(rate(traefik_service_requests_total{protocol!=\"websocket\", code=~\"5..\"}[$interval])) by (code)",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "Traefik v1 error codes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(traefik_backend_requests_total{code=~\"4..\"}[$interval])) by (code)",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "Traefik v2 request duration",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(traefik_service_request_duration_seconds_sum{protocol!=\"websocket\"}) / sum(traefik_entrypoint_requests_total{protocol!=\"websocket\"}) * 1000",
     "legendFormat": "Traefik request duration"
    }
   ]
  },
  {
   "title": "Traefik v1 request duration",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(traefik_backend_request_duration_seconds_sum{protocol!=\"websocket\"}[5m])) / sum(rate(traefik_backend_request_duration_seconds_count{protocol!=\"websocket\"}[5m]))",
     "legendFormat": "Traefik request duration"
    }
   ]
  }
 ]
}