{
 "title": "Traefik",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Traefik 5XX",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(traefik_backend_requests_total{code=~\"5..\"}[5m]))",
     "legendFormat": "5XX"
    }
   ]
  },
  {
   "title": "Traefik 5XX by backend",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(traefik_backend_requests_total{code=~\"5..\"}[5m])) by (backend)",
     "legendFormat": "5XX : {{backend}}"
    }
   ]
  },
  {
   "title": "Traefik request duration",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(traefik_backend_request_duration_seconds_sum{protocol!=\"websocket\"}[5m])) / sum(rate(traefik_backend_request_duration_seconds_count{protocol!=\"websocket\"}[5m]))",
     "legendFormat": "Traefik request duration"
    }
   ]
  },
  {
   "title": "Traefik request duration by backend",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(traefik_backend_request_duration_seconds_sum{protocol!=\"websocket\"}[5m])) by (backend) / sum(rate(traefik_backend_request_duration_seconds_count{protocol!=\"websocket\"}[5m])) by (backend)",
     "legendFormat": "Traefik request duration :  {{backend}}"
    }
   ]
  }
 ]
}