{
 "title": "Traefik - Blue/Green Deployment",
 "tags": [ "traefik" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Entrypoint requests per minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(traefik_entrypoint_requests_total{namespace=\"traefik-blue-variant\"}[1m]))",
     "legendFormat": "Blue"
    },
    {
     "expr": "sum(rate(traefik_entrypoint_requests_total{namespace=\"traefik-green-variant\"}[1m]))",
     "legendFormat": "Green"
    }
   ]
  },
  {
   "title": "Service requests per minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(traefik_service_requests_total{namespace=\"traefik-blue-variant\"}[1m]))",
     "legendFormat": "Blue"
    },
    {
     "expr": "sum(rate(traefik_service_requests_total{namespace=\"traefik-green-variant\"}[1m]))",
     "legendFormat": "Green"
    }
   ]
  },
  {
   "title": "Row title",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {}
   ]
  },
  {
   "title": "5XX error rate",
   "type": "stat",
   "description": "Rate of 5XX errors amongst all entry point requests.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(traefik_entrypoint_requests_total{entrypoint=\"web\",namespace=\"traefik-blue-variant\", code=~\"[5][0-9]{2}\"}[1m]))*100/sum(rate(traefik_entrypoint_requests_total{entrypoint=\"web\",namespace=\"traefik-blue-variant\"}[1m]))",
     "legendFormat": "Blue"
    },
    {
     "expr": "sum(rate(traefik_entrypoint_requests_total{entrypoint=\"web\",namespace=\"traefik-green-variant\", code=~\"[5][0-9]{2}\"}[1m]))*100/sum(rate(traefik_entrypoint_requests_total{entrypoint=\"web\",namespace=\"traefik-green-variant\"}[1m]))",
     "legendFormat": "Green"
    }
   ]
  }
 ]
}