{
 "title": "Kiosk",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  { "title": "Requests served", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "API requests served (Kubernetes-only)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(traefik_entrypoint_requests_total{entrypoint=\"web\"}[1d]))",
     "legendFormat": "Request rate"
    }
   ]
  },
  {
   "title": "Kafka Events - Sent (per hour)",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 10, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(confluent_kafka_server_received_records[1h]))",
     "legendFormat": "Kafka Events Sent"
    }
   ]
  },
  {
   "title": "Topics (≅)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "topics" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(confluent_kafka_server_partition_count)/2.5",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Kafka Events - Received (per hour)",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 10, "x": 10, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(confluent_kafka_server_sent_records[15m]))",
     "legendFormat": "Kafka Events Received"
    }
   ]
  },
  {
   "title": "AWS Databases",
   "type": "piechart",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(aws_rds_db_total)", "legendFormat": "AWS RDS" },
    { "expr": "sum(aws_dynamodb_table_total)", "legendFormat": "AWS DynamoDB" }
   ]
  },
  { "title": "Platform Totals", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "AWS Unique Platform Users",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "developers" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(aws_sso_exporter_authenticate_unique_users) by (name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Platform sign-ins (over 30 days)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 6, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "sign-ins" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(aws_sso_exporter_authenticate_total_signins) by (name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Capabilities / Unique Business Services",
   "type": "stat",
   "description": "Approximates capabilities by counting namespaces. This is roughly, but unrelated, the same as counting capabilities outside of ti-arch",
   "gridPos": { "h": 4, "w": 5, "x": 11, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "capabilities" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_namespace_created{namespace=~\".*-[a-z]{5}$\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Documentation articles available",
   "type": "stat",
   "description": "wiki.dfds.cloud",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "articles" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "208", "legendFormat": "__auto" }
   ]
  },
  { "title": "Product rollout", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "RDS Blueprints Coverage",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(sum(blueprints_aws_rds_db_total)) / (sum(aws_rds_db_total) / 100)",
     "legendFormat": "RDS Blueprints Coverage %"
    }
   ]
  },
  {
   "title": "1Password users",
   "type": "stat",
   "description": "Fix when moved to grafana cloud",
   "gridPos": { "h": 4, "w": 5, "x": 6, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "180", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "1Password Shared Items",
   "type": "stat",
   "description": "Fix when moved to grafana cloud",
   "gridPos": { "h": 4, "w": 5, "x": 11, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "1025", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Services Available (Kubernetes-only)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "services" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_service_created{namespace!~\"kube-system\", namespace!~\"developer-auto.*\", service!~\".*kube.*\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}